site:
  title: Self-Help Guide
  url: https://example.com
  start_page: shg::index.adoc
  robots: allow
  # google tags: see couchbase docs for example
  # keys: 
  #   google_analytics: 'GTM-032462'
content:
  sources:
    - url: .
    # - url: https://github.com/tdewolf/self-help-guide.git
      branches: ['main', 'release/1.0']
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    #url: ../../gitlab/dd-docs-ui/build/ui-bundle.zip
    snapshot: true
  #supplemental_files: ./supplemental-ui
antora:
  extensions:
  - '@antora/lunr-extension'
  - require: './lib/unused-sources.js'
    add_to_navigation: false
    unlisted_pages_heading: Orphans
