= Various

Some various content about using and customizing Antora.

== No default page layout

=== Issue

Building your documentation project fails with error 'No default page layout'.

=== Cause

Create ui-bundle.zip file is empty (22 bytes), most likely because there are some missing files in the root of the repo, f.e. .stylelintrc and .eslintrc

=== Resolution

When you start from the link:https://gitlab.com/antora/antora-ui-default.git[default antora ui project], ensure that you have all files in your repo. During the packaging of ui-bundle.zip, the files that will be included will be checked by a linter. If the lint configurations are not available, no files are added and will result in an empty zip file.


== CSS changes not applied

=== Issue

When you customize the UI, you have to apply changes to the files in src/ folder, f.e. src/css or src/partials. However, when creating the new bundle and building the documentation again, you don't see the changes.

=== Cause

The ui-bundle.zip file contains the public folder instead of the src folder.

=== Resolution

Before packaging ui-bundle.zip, ensure that you have removed the public folder from the root of the repository.


== Target not found

=== Issue

Xref link does not work.

=== Cause

You used the relative path to the target.

=== Resolution

Creating xref links to other modules does not work when using the relative path to the target.

Instead use the following structure:

```
xref:<version>@<component>:<module>:<page>.adoc[<optional display text>]
```

Where all values are optional. Go to the https://docs.antora.org/antora/latest/page/page-links/[Antora documentation] for more details.


== target of include not found

Even though Intellij correctly displays the included content, building the docs reports errors on includes not found.

=== Cause

The version in the antora.yml of the shared module is different from the other modules.

=== Resolution

Ensure that the version of all modules is identical.