= UI Macros
:experimental:
:icons: font
:iconmacro: https://docs.asciidoctor.org/asciidoc/latest/macros/icon-macro/

== Button syntax

Press btn:[Submit] to send your responses.


== Keyboard keys

Press kbd:[Ctrl+C] to copy the selection to the clipboard.


== Menu syntax

Go to menu:File[Save] to save the changes.

Go to menu:File[Share,Messages]


== Sidebars

This is a sidebar:

[sidebar]
Sidebars are used to visually separate text to supplement the main text.


== Font awesome icons

You can easily add fontawesome icons in your sources. To do so:

. Add at the top of the page: `:icon: font`.
. In your source add an icon: \icon:fontawesomename[] +
where <fontawesomename> is the fontawesome icon name. You can find the list of icons and their corresponding names on this page: https://fontawesome.com/v4/icons/.

The advantage of adding icons this way in your sources is that you can add attributes to the icon, for example, change the size or the color.

EXAMPLE:: \icon:heart[role=red] results in a red heart icon in the output: icon:heart[role=red].

NOTE:: IntelliJ only shows the icon, not the attributes.

For more information about the icon macro, go to the Asciidoctor link:iconmacro[Icon macro] documentation.