:experimental:
:icons: font

= Various

== Conditionals

You can add conditional content with the `ifdef` and `ifndef` macros.

This can be helpful when single-sourcing when there are bits that should be shown in one situation and hidden in another.

For the full documentation, go to the link:https://docs.asciidoctor.org/asciidoc/latest/directives/ifdef-ifndef/[asciidoctor documentation].

A simple example would be the usage of showing content in html but not in pdf.

[source,adoc]
....
\ifdef::pdf[]
Do only show in PDF output
\endif::pdf[]
....


In some situations, the `pdf` part is a variable that is set at the top of the page and the content between the `ifdef` and `endif` directives is a partial.

Your source could look like this:

[source,asciidoc]
....
:pdf:

= heading 1

\ifdef::pdf[]
\include::partial$a-partial-here.adoc[]
\endif::pdf[]
....

Now, it is possible to set a directive just before a section, but then that directive remains active for all subsequent content and asciidoc files (following the index or navigation file). If the directive should be reset after being used, you have to reset it. In the following example, we use a new images directory for a specific section (`:imagesdir: rest/`), but then reset it to the original one. To do so, you first store the original images directory in another variable (`:originalimagesdir: {imagesdir}`) and then assign this new variable back to the original one (`:imagesdir: {originalimagesdir}`).


[source,asciidoc]
....
:originalimagesdir: {imagesdir}
:imagesdir: rest/
\include::rest/resources.adoc[]
\include::rest/types.adoc[]
:imagesdir: {originalimagesdir}
....
