= Delimited blocks
:examplesdir: ../examples

Specific blocks in Asciidoc +
This is for {company}.

== Code block

Code block is defined by `----`.

\`----` +
your code here +
\`----`

results in:
----
your code here
----

== Overview block delimiters

* comment: ////
* example: ====
* literal: ....
* listing, source code: ----
* open: --
* pass: ++++
* quote, verse: ____
* sidebar: ****
* table: |===

Then there is the open block delimiter (--), which is specifically for capturing content in a div that can masquerade as pretty much any block type, but on its own it has no semantic other than "grouping" the contents. I mostly use it like:

....
some term::
+
--
First paragraph.

Second paragraph.
--
....

But of course, you could also use a + alone on a line between those paragraphs, to the same effect, which doesn't seem to work for all masquerade blocks. Most masquerades either need delimiters or they are confined to one contiguous block
....
[listing]
Some text.
Some more text in the same literal block.
+
But this will break off and be a regular paragraph?
....

(I actually thought the + notation would work there. I swear I used to do admonitions that way, but it doesn't seem to work in VSC preview or in AsciiDocAlive.)
And admonitions get their expected handling when used with `====` as they would with no delimiter, so it's a good convention to use those.
I don't think it makes sense to use open block notation for anything but generic blocks. I do think sticking to the semantic delimiters is best.


== Block metadata

You can add metadata to the above-mentioned blocks. Here's an overview.

* Title: .Your Title Here
* ID (anchor): [[anchor_name_here]]
* Style: between square brackets, usually combined with the named block attributes
* Named block attributes

== Source code blocks

Add syntax highlighting via metadata:

[source,ruby]
----
require 'asciidoctor'

puts Asciidoctor.convert_file 'mysample.adoc', to_file: false
----

You can also include a real source code file with the include macro:

[source,ruby]
----
include::{examplesdir}/example.rb[]
----

You can even add callouts in your source code.

[source,ruby]
----
require 'asciidoctor'  # <1>

Asciidoctor.convert_file 'mysample.adoc'  # <2>
----
<1> Imports the library
<2> Reads, parses, and converts the file

== Open blocks

Can be any block except pass and table.

Example of open block acting as a sidebar.

[sidebar]
.Related information
--
This is aside text.

It is used to present information related to the main content.
--

== TOC block

You can add a page TOC at the top of your page by adding the following snippet at the top of your asciidoc page:

----
ifndef::env-idea[]
:toc: left
endif::env-idea[]
----
