:experimental:
:icons: font
:iconmacro: https://docs.asciidoctor.org/asciidoc/latest/macros/icon-macro/

= UI Macros

== Button syntax

Press btn:[Submit] to send your responses.


== Keyboard keys

Press kbd:[Ctrl+C] to copy the selection to the clipboard.


== Menu syntax

Go to \menu:File[Save] to save the changes.

Go to \menu:File[Share,Messages]


== Sidebars

This is a sidebar:

[sidebar]
Sidebars are used to visually separate text to supplement the main text.


== Font awesome icons

You can easily add fontawesome icons in your sources. To do so:

. Add at the top of the page: `:icons: font`.
. In your source add an icon: \icon:fontawesomename[] +
where <fontawesomename> is the fontawesome icon name. You can find the list of icons and their corresponding names on this page: https://fontawesome.com/v6/icons/.

The advantage of adding icons this way in your sources is that you can add attributes to the icon, for example, change the size or the color.

EXAMPLE:: \icon:heart[role=red] results in a red heart icon in the output: icon:heart[role=red].

NOTE:: IntelliJ only shows the icon, not the attributes.

For more information about the icon macro, go to the Asciidoctor {iconmacro}[Icon macro] documentation.

=== Most used font-awesome icons

[options="header"]
|===
| name | icon

| plus | icon:plus[]
| minus | icon:minus[]
| arrow-up | icon:arrow-up[]
| arrow-down | icon:arrow-down[]
| arrow-left | icon:arrow-left[]
| arrow-right | icon:arrow-right[]
| check | icon:check[]
| close | icon:close[]
| toggle-on | icon:toggle-on[]
| toggle-off | icon:toggle-off[]
| upload | icon:upload[]
| download | icon:download[]
| cog | icon:cog[]
| refresh | icon:refresh[]
| bar-chart | icon:bar-chart[]
| angle-down, angle-left, angle-right, angle-up | icon:angle-down[], icon:angle-left[], icon:angle-right[], icon:angle-up[]
| arrows | icon:arrows[]
| caret-up | icon:caret-up[]
| caret-down | icon:caret-down[]
| ellipsis | icon:ellipsis[]
| ellipsis-h | icon:ellipsis-h[]
| pen-to-square | icon:pen-to-square[]
| play | icon:play[]
| stop | icon:stop[]
|===