:experimental:
:icons: font

= Various

== Conditionals

You can add conditional content with the `ifdef` and `ifndef` macros.

This can be helpful when single-sourcing when there are bits that should be shown in one situation and hidden in another.

For the full documentation, go to the link:https://docs.asciidoctor.org/asciidoc/latest/directives/ifdef-ifndef/[asciidoctor documentation].

A simple example would be the usage of showing content in html but not in pdf.

----
\ifdef::pdf[]
Do only show in PDF output
\endif::pdf[]
----

In some situations, the `pdf` part is a variable that is set at the top of the page and the content between the `ifdef` and `endif` directives is a partial.

Your source could look like this:

----
:pdf:

= heading 1

\ifdef::pdf[]
\include::partial$a-partial-here.adoc[]
\endif::pdf[]
----

Now, it is possible to set a directive just before a section, but then that directive remains active for all subsequent content and asciidoc files (following the index or navigation file). If the directive should be reset after being used, you have to reset it. In the following example, we use a new images directory for a specific section (`:imagesdir: rest/`), but then reset it to the original one. To do so, you first store the original images directory in another variable (`:originalimagesdir: {imagesdir}`) and then assign this new variable back to the original one (`:imagesdir: {originalimagesdir}`).


----
:originalimagesdir: {imagesdir}
:imagesdir: rest/
\include::rest/resources.adoc[]
\include::rest/types.adoc[]
:imagesdir: {originalimagesdir}
----


== Select content to be included

If you use the `include` directive, you include the full file that you selected. However, you can apply tags on the source to make a selective include.

For example, if you have a topic (toBeIncluded.adoc) with 3 paragraphs, and you want to include all 3 in one topic (topicA.adoc) but only the first two in another topic (topicB.adoc), then you need to apply tags.

In toBeIncluded.adoc, apply a tag (`topicB-only`) to the relevant paragraphs:

----
tag::topicB-only[]
My paragraph 1

My paragraph 2
end::topicB-only[]

My paragraph 3
----

To include all content to topicA.adoc:

----
\include::toBeIncluded.adoc[tag=**]
----

To include only the tagged content in topicB.adoc:

----
\include::toBeIncluded.adoc[tag=topicB-only]
----

For more information, see the https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/[asciidoctor documentation].


== Including content from another repository

If you have topics that must be shared between different repositories, you can still share them as if they were in the same repository. The downside is that you will not see the content of the included topic if the topic is saved in the other repo.

To do so, you must use the same structure in both repositories, so don't mix an antora repo structure with a non-antora structure.

Suppose we store the shared content in RepositoryA in a `shared` project.


=== Example

----
RepositoryA
 `- docs
    `- projectA1
       `- modules
          `- ROOT
             `- pages
                `- repoA-pA1-topic1.adoc
    `- shared
       `- modules
          `- ROOT
             `- partials
                `- shared-content.adoc
----

----
RepositoryB
 `- docs
    `- projectB1
       `- modules
          `- ROOT
             `- pages
                `- repoB-pB1-topic1.adoc
----

If you want to include the shared-content.adoc in the topic repoB-pB1-topic1.adoc, you can do:

----
\include::shared::partial$shared-content.adoc[]
----

You will get an error that the file cannot be resolved but if they would be combined in the same playbook, then the included file will show up in the repoB-pB1-topic1.adoc topic.